### ISSUE TITLE
VM again

### ISSUE THREAD

**Issue by philxdes** [t3l3machus/Villain#124]
Hey its me again, so the bridged adapter worked perfectly well when its pcs on my own network, but if i try it on a pc that is on a different location/router it does not recieve anything.  Any ideas?  Me and my friend have been trying to figure this one out for a little bit now.  thanks

**Comment by t3l3machus** [comment]
In order to establish cross network communications, you need to implement the appropriate routes. Villain uses (by default) port 6501 to connect with others, and ports 4443 & 8080 to catch incoming shells. These ports must be publicly accessible on the machine(s) you are running Villain in order to work. To do that, you have to log in to your router's interface and navigate to the port forwarding menu, usually called "Virtual Servers" (it could have other names depending on the router, you must look around to locate it). From there, you can set a public port on your router to redirect all traffic to a specified host (ip) and port in your LAN. After you set port forwarding correctly for the 3 ports i mentioned, Villaint will work fine. I suggest you first try setting up a simple python or apache http server, configure the port forwarding and verify it works by accessing the server using your public ip address.
