### ISSUE TITLE
issue with upload command

### ISSUE THREAD

**Issue by dr1408** [t3l3machus/Villain#172]
Thanks for great project .. i am using it with kali nethunter and i use pplayit for port forwarding ..  i forwarded the netcat port 4443 and  i ccan recieve backdoor connection but when i try to upload file it sshow me this error 
![601723FC-2C13-4C98-A3A2-3133F2BF1120](https://github.com/user-attachments/assets/61b28650-797b-4c5c-9c98-852ab9a04253)

**Comment by t3l3machus** [comment]
Hi @dr1408, thanks! That's because you didn't port forward the file smuggler port as well (that's where the file is requested from). Unfortunately, even if you do port forward 8888, the upload won't work because of a known issue I will fix this week (long story short, if you are using a public IP, the file smuggler IP must be set accordingly, but at the moment it uses the reverse connection's iface IP).

Fyi, major update coming later today, it will make Villain a lot more reliable and stable.

**Comment by dr1408** [comment]
Thanks for response sir .. i used another port for smugller which already forwarded as you said it will not work im excited about the update good luck and thanks again 🙏🏼

**Comment by dr1408** [comment]
Good evening , Is it fixed in last update sir ? have a great day
