### ISSUE TITLE
payload session ID issue

### ISSUE THREAD

**Issue by salnaggar** [t3l3machus/Villain#29]
every time i run 

generate os=windows lhost=eth0 

it create payload with unique session ID and it will work only on one target, i can't execute same payload on 2 targets i have to create payload for each target separately!!

how to allow same payload to be executed on multiple targets at the same time??

Thank you

**Comment by salnaggar** [comment]
the payloads are disposables lol i can use them one time and i have to create payload for each target... i hope you fix that thing

**Comment by t3l3machus** [comment]
This is not an issue, it was designed this way. If the Villain server accepts any session ID not necessarily generated by it then someone can use the payload to plant sessions in a Villain instance. But since many people have requested for an option to make session ids reusable, i will implement it in a future update. This also clearly mentioned in the README:
![image](https://user-images.githubusercontent.com/75489922/205511030-970c74e0-1cdf-41e5-a8ef-ed91493fe5b8.png)

**Comment by salnaggar** [comment]
Thank you :)
i'll try to add that myself with some help from my best friend ChatGPT

**Comment by t3l3machus** [comment]
Actually, in a few days or so I will release a new version that includes netcat listener support. Basically you will be able to grab reverse shells from netcat-listener based payloads as well and those will be reusable. So maybe that solves your issue
