### ISSUE TITLE
Generate the same payload each time.

### ISSUE THREAD

**Issue by Blast02** [t3l3machus/Villain#85]
Hello, I wanted to try the tool on a windows 10 but the obfuscate function does not work and generates the same payload each time.
If you can explain to me why that would be nice.

**Comment by t3l3machus** [comment]
@Blast02 the `generate` function was redesigned. You can still use the "obfuscate" keyword for windows/hoaxshell/powershell* payloads. 

![image](https://user-images.githubusercontent.com/75489922/229339178-a88d991e-eb29-4a7d-b1e0-38f7a4e705ae.png)

You can enable it for TCP socket type of payloads as well if you edit the templates and set "obfuscate" to True in the `attrs` but the obfuscator class has not been properly adjusted to work with them, meaning, sometimes it will generate obfuscated versions that may not work because of syntax errors.

![image](https://user-images.githubusercontent.com/75489922/229339375-cc212f54-a841-420b-8712-e1bb36d6209f.png)
