### ISSUE TITLE
The problem of switching directory after session goes in

### ISSUE THREAD

**Issue by ffsfwnuiaww** [t3l3machus/Villain#95]
<img width="204" alt="image" src="https://user-images.githubusercontent.com/89639412/234239692-6e6c08ad-c44d-4636-b523-d13e95fac5f5.png">

**Comment by ffsfwnuiaww** [comment]
i test in hoaxshell ，It is found that it cannot switch the directory normally


and test in netcat，It is found that it can switch the directory normally

<img width="539" alt="image" src="https://user-images.githubusercontent.com/89639412/234247336-0565dc70-5261-4798-b4ba-5b35deae0c0e.png">

**Comment by t3l3machus** [comment]
This has to do with the stability of a given shell session. Unstable reverse shells might not support directory traversal. All hoaxshell reverse shells are marked as unstable because they are. You should prefer Villain's TCP handler which was designed to accept various reverse shell connections that may originate from netcat/msfvenom/script commands and executables. Still not perfect but much better than hoaxshell
