### ISSUE TITLE
Prob a simple issue to fix :)

### ISSUE THREAD

**Issue by ghost** [t3l3machus/Villain#96]
Hey whats up?
So ive been playing around with Villain and i got these errors, (im connected via ssh to a raspberrypi with villain on it so thats prob why i get the missing symbol thingy) it works when i copy paste it to powershell but when i pull it from my github repository its wonky and gives me these errors. Im assuming that peers is a connected Villain machine but i havent shared any shells/connected to anyone. Thanks for the help :). (Btw ive obfuscated it like in ur videos but it works when i copy paste so i doubt thats the problem.)

[Error] Failed to establish a backdoor session: Connection reset by peer.
[Error] Failed to establish a backdoor session: ConnectionResetError.
Villain >

**Comment by 0067sdsm** [comment]
i am runing the raspberrian simple 32 bit one (i think the names something like that), its only the terminal, and as for being able to reach it it can because they are on the same network and it had also worked before. Im pretty sure it has something to do with the iisues ive been having setting up a static ip and port forwarding, ill try again after i get those figured out. Thanks :).
